---
title: "Ski Conditions Dashboard"
output: html_notebook
---

 
### Load rnoaa API package
```{r}
library(tidyverse)
library(rnoaa)
library(lubridate)
library(ggplot2)
library(ggthemes)
library(scales)
library(shiny)
library(shinydashboard)
library(plotly)
library(leaflet)
library(rsconnect)
theme_set(theme_minimal())
key <- "oWIiLBATPGoafvkxmNwWOOCcmIOBVmOC"
```

### create Station Dataframe
```{r}
meteo_clear_cache(force = FALSE)

my_stations <- data.frame(
  mountain = c(
               "Mt Hood, Oregon, USA",
               "Mt Hood, Oregon, USA",
               "Mt Hood, Oregon, USA", 
               "Mt Baker, Washington, USA",
               "Mt Baker, Washington, USA",
               "Mt Baker, Washington, USA",
               "Mt Bachelor, Oregon, USA",
               "Mt Bachelor, Oregon, USA",
               "Mt Bachelor, Oregon, USA",
               "White Pass, Washington, USA",
               "White Pass, Washington, USA",
               "White Pass, Washington, USA",
               "Schweitzer, Idaho, USA",
               "Schweitzer, Idaho, USA",
               "Schweitzer, Idaho, USA",
               "Tahoe, California, USA",
               "Tahoe, California, USA",
               "Tahoe, California, USA"),
  
  id = c(
               "USC00358530",
               "USS0021D08S",
               "USC00353402",
               "USC00455663",
               "USC00459294",
               "USS0021A31S",
               "USR0000OBEN",
               "US1ORDS0034",
               "USS0021E13S",
               "USS0021C28S",
               "USS0021C33S",
               "USC00458653",
               "USS0016A10S",
               "USS0016A13S",
               "US1IDBR0013",
               "USC00048474",
               "USS0020K30S",
               "USS0020K25S"))
```

### Use to find possible Elevation by Station
```{r}
### Create for loop vars
y <- paste('GHCND',my_stations$id,sep = ":")
count <- 0
stations <- vector('list', length = length(my_stations$id))

### Gather Data for Each Station
for (i in seq_along(y))
{
    stations[[i]] <- ncdc_stations(datasetid='GHCND', 
                     stationid = y[[i]],
                     token = key)
    count + 1
}


### Parse data to Dataframe
stations_demographic <- 
  data.frame(matrix(unlist(stations), nrow=length(stations), byrow=T))

colnames(stations_demographic) <- 
  c("elevation", 
    "mindate", 
    "maxdate", 
    "latitude", 
    "name", 
    "datacoverage", 
    "GHCND_id", 
    "elevationUnit", 
    "longitude"
    )

### Create elevation in ft, split ID, filter date
stations_demographic <- stations_demographic %>% 
  separate(GHCND_id, c("type","id"), sep = ":", remove = FALSE) %>% 
  select(-c("mindate", "maxdate", "type", "elevationUnit")) %>% 
  rename(elevationMeter = elevation) %>% 
  left_join(my_stations, by = c("id" = "id"))

```


### Metric Conversion Formulas
```{r}
farenheit <- function(celcius){
  (celcius/10)*(9/5)+32
}

inch_rain <- function(millimeter){
  (millimeter/10)/25.4
}

inch_snow <- function(snow){
  snow/25.4
}

#### Add function for SWE equivalency and estimae snow density.
snw_density <- function(swe,snwd){
  (swe/snwd)*100
}

elevation_ft <- function(elevation){
  as.numeric(as.character(elevation)) * 3.28984
}


```

### Create Final Data Set
```{r, message=FALSE}

obs <- meteo_pull_monitors(my_stations$id, date_min = '2016-11-01' ) %>% 
   left_join(stations_demographic, by = c("id" = "id")) %>% 
   select(-c("awnd","wsfi","wesf","awdr","mdpr","dapr","snow"))


```

### Convert from metric system
```{r}

obs_final <- obs %>% 
  mutate(tavg = farenheit(tavg),
         tmin = farenheit(tmin),
         tmax = farenheit(tmax),
         tobs = farenheit(tobs),
         prcp = inch_rain(prcp),
         snwd = inch_snow(snwd),
         wesd = inch_rain(wesd),
         elevationFt = elevation_ft(elevationMeter),
         snw_dens = snw_density(wesd,snwd),
         latitude = as.numeric(as.character(latitude)),
         longitude = as.numeric(as.character(longitude))
         ) %>% 
  filter(!is.na(tavg))


```

### Temp Data Frame
```{r}
temp_final <- obs_final %>% 
  select(mountain, name, date,tmax, tmin) %>% 
  gather(key = temptype, value = temp, c(tmax,tmin))


```


### Shiny Workspace
```{r, message=FALSE}
ui <- dashboardPage(
  dashboardHeader(title = "Ski Conditions Dashboard"),
  dashboardSidebar(
    
      selectInput("select", 
                  h3("Select Mountain"), 
                  choices = list("Mt Hood, Oregon, USA" = 1, 
                                 "Mt Baker, Washington, USA" = 2,
                                 "Mt Bachelor, Oregon, USA" = 3, 
                                 "White Pass, Washington, USA" = 4, 
                                 "Schweitzer, Idaho, USA" = 5, 
                                 "Tahoe, California, USA" = 6), 
                                  selected = 1),
    

    
      dateRangeInput("date", 
                       h3("Select a Date Range"), 
                       start = Sys.Date()-550, 
                       end = Sys.Date(),
                       format = "yyyy-mm-dd", 
                       startview = "month", 
                       weekstart = 0,
                       language = "en" )
                ),
  dashboardBody(
    
              # Frontpage - boxes - start -----------------------------------------------
    fluidRow(
      
          valueBoxOutput("date_out"),
          valueBoxOutput("depth_out"),
          valueBoxOutput("density")
          ),

          # Frontpage - boxes - end -------------------------------------------------
        
         # Box layout - Grid - Start
#-------------------------------------------------
    fluidRow(
      box(leafletOutput("map", height = 400)),
      box(plotlyOutput("temp", height = 400)),
      box(plotlyOutput("snowdepth", height = 400)),
      box(plotlyOutput("prcp", height = 400))

    )
          #Box layout - Grid - end #------------------------------------------------- 
  )
)

server <- function(input, output) {
  
  ### Snow Depth Chart
  output$snowdepth <- renderPlotly({
      data <- switch(input$select,
           "1" = obs_final %>% filter(mountain == "Mt Hood, Oregon, USA"),
           "3" = obs_final %>% filter(mountain == "Mt Bachelor, Oregon, USA"),
           "2" = obs_final %>% filter(mountain == "Mt Baker, Washington, USA"),
           "4" = obs_final %>% filter(mountain == "White Pass, Washington, USA"),
           "5" = obs_final %>% filter(mountain == "Schweitzer, Idaho, USA"),
           "6" = obs_final %>% filter(mountain == "Tahoe, California, USA"))
      
     p <- ggplot(data,aes(date,snwd))+
        geom_area(aes(fill=name),size=1)+
        scale_x_date(limits = c(input$date[1], input$date[2]))+
        theme(legend.position="none",
              axis.title.x=element_blank(),
              axis.title.y=element_blank())+
        ggtitle("Snow Depth by Station (Inches)")+ 
        scale_fill_manual(values = c("#6794a7", "#76c0c1"))
      
    
     ggplotly(p)
  })
   
  ### Station Location Map 
  output$map <- renderLeaflet({
    
      data <- switch(input$select,
           "1" = obs_final %>% filter(mountain == "Mt Hood, Oregon, USA"),
           "3" = obs_final %>% filter(mountain == "Mt Bachelor, Oregon, USA"),
           "2" = obs_final %>% filter(mountain == "Mt Baker, Washington, USA"),
           "4" = obs_final %>% filter(mountain == "White Pass, Washington, USA"),
           "5" = obs_final %>% filter(mountain == "Schweitzer, Idaho, USA"),
           "6" = obs_final %>% filter(mountain == "Tahoe, California, USA"))
      
    title <- "Weather Station Locations (click Marker for Info)"   
    content <- paste(sep = "<br/>",
        paste("Ski Resort: ", data$mountain),                 
        paste("Station: ",data$name),
        paste("Elevation: ",data$elevationFt))
  
    leaflet() %>%
    addTiles() %>% 
    addMarkers(lng= data$longitude, lat= data$latitude, popup = content) %>% 
    addControl(title, position = "topright")
  })
  
  ### Temp Chart
  output$temp <- renderPlotly({
  
    temp_final <- switch(input$select,
           "1" = temp_final %>% filter(mountain == "Mt Hood, Oregon, USA"),
           "3" = temp_final %>% filter(mountain == "Mt Bachelor, Oregon, USA"),
           "2" = temp_final %>% filter(mountain == "Mt Baker, Washington, USA"),
           "4" = temp_final %>% filter(mountain == "White Pass, Washington, USA"),
           "5" = temp_final %>% filter(mountain == "Schweitzer, Idaho, USA"),
           "6" = temp_final %>% filter(mountain == "Tahoe, California, USA"))
    
 f <- ggplot(temp_final,aes(date,temp))+
        geom_line(aes(color=temptype))+
        scale_x_date(limits = c(input$date[1], input$date[2]))+
        theme(legend.position="none",
              axis.title.x=element_blank(),
              axis.title.y=element_blank())+
        ggtitle("High-Low Temperature by Station (Farenheit)")+
        scale_color_economist()
        ggplotly(f)
        
        
  
})
  
  ### PRCP Chart
  output$prcp <- renderPlotly({
  
     prcp_final <- switch(input$select,
           "1" = obs_final %>% filter(mountain == "Mt Hood, Oregon, USA"),
           "3" = obs_final %>% filter(mountain == "Mt Bachelor, Oregon, USA"),
           "2" = obs_final %>% filter(mountain == "Mt Baker, Washington, USA"),
           "4" = obs_final %>% filter(mountain == "White Pass, Washington, USA"),
           "5" = obs_final %>% filter(mountain == "Schweitzer, Idaho, USA"),
           "6" = obs_final %>% filter(mountain == "Tahoe, California, USA"))
    
 q <- ggplot(prcp_final,aes(date,prcp))+
        geom_line(aes(color=name), size=1)+
        scale_x_date(limits = c(input$date[1], input$date[2]))+
        theme(legend.position="none",
              axis.title.x=element_blank(),
              axis.title.y=element_blank())+
        ggtitle("Precipitation by Station (Inches)") +   
        scale_color_economist()
        
     ggplotly(q)
  

  
})

  ### Max Date Value Box
  output$date_out <- renderValueBox({
  date_df <-  switch(input$select,
           "1" = obs_final %>% filter(mountain == "Mt Hood, Oregon, USA"),
           "3" = obs_final %>% filter(mountain == "Mt Bachelor, Oregon, USA"),
           "2" = obs_final %>% filter(mountain == "Mt Baker, Washington, USA"),
           "4" = obs_final %>% filter(mountain == "White Pass, Washington, USA"),
           "5" = obs_final %>% filter(mountain == "Schweitzer, Idaho, USA"),
           "6" = obs_final %>% filter(mountain == "Tahoe, California, USA")) %>% 
  filter(!is.na(date),!is.na(snwd))
  
  valueBox(
    date_df %>% 
    filter(elevationFt == max(elevationFt)) %>% 
    filter(date == max(date)) %>% 
    select(date) %>% 
      mutate(date = paste(month(date, label = TRUE, abbr = FALSE),day(date),year(date))),
      "Last Snow Depth Reading",
            color = "blue",
            icon = icon("calendar-alt"),
            width = 2
         )
})

  ### Depth Change Value Box
  output$depth_out <- renderValueBox({
  
  data_depth <- switch(input$select,
           "1" = obs_final %>% filter(mountain == "Mt Hood, Oregon, USA"),
           "3" = obs_final %>% filter(mountain == "Mt Bachelor, Oregon, USA"),
           "2" = obs_final %>% filter(mountain == "Mt Baker, Washington, USA"),
           "4" = obs_final %>% filter(mountain == "White Pass, Washington, USA"),
           "5" = obs_final %>% filter(mountain == "Schweitzer, Idaho, USA"),
           "6" = obs_final %>% filter(mountain == "Tahoe, California, USA")) %>% 
  filter(!is.na(date),!is.na(snwd))
 
 depth_find <- function(df){
 x <- df %>% filter(elevationFt == max(elevationFt)) %>% 
   filter(date == max(date)) %>% 
   select(snwd) 
 y <- df %>% filter(elevationFt == max(elevationFt)) %>% 
             filter(date == min(date)) %>% 
             select(snwd)
 
 change <- x-y
 change <- as.integer(change)
 return(change)
 }
 
depth <- data_depth %>% 
    select(date,snwd,elevationFt) %>% 
    filter(date <= max(date),date >= max(date)-4, !is.na(snwd)) %>% 
    depth_find()
 
  valueBox(paste(depth," Inches"),
    "Snow Depth Change in last 4 days",
            color = "light-blue",
            icon = icon("snowflake"),
            width = 2
  )
})

  ### Last Recorded Snow Density
  output$density <- renderValueBox({
  
  data_dens <- switch(input$select,
           "1" = obs_final %>% filter(mountain == "Mt Hood, Oregon, USA"),
           "3" = obs_final %>% filter(mountain == "Mt Bachelor, Oregon, USA"),
           "2" = obs_final %>% filter(mountain == "Mt Baker, Washington, USA"),
           "4" = obs_final %>% filter(mountain == "White Pass, Washington, USA"),
           "5" = obs_final %>% filter(mountain == "Schweitzer, Idaho, USA"),
           "6" = obs_final %>% filter(mountain == "Tahoe, California, USA")) %>% 
   filter(!is.na(snw_dens))
 
 dens_find <- function(df){
 x <- df %>% filter(elevationFt == max(elevationFt)) %>% 
   filter(date == max(date)) %>%
   select(snw_dens)
 return(as.integer(x))
 }
 
 icon_func <- function(d){
   ifelse(d > 30, return(icon("thumbs-down")),return(icon("thumbs-up")))
 }
 
 d <- data_dens %>% 
    select(date,snw_dens,elevationFt) %>% 
    dens_find()
 
  valueBox(paste(d,"%"),
    "Current Snow Density",
            color = "aqua",
            icon = icon_func(d),
            width = 3
            
    
  )
})

}

shinyApp(ui, server)
```

